name: Stablecoin YieldBot Group 1

on:
  schedule:
    # Run once per day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/puppeteer/puppeteer:21.7.0
      options: --shm-size=2gb
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          npm install axios
          
      - name: Run YieldBot Group1
        run: node yieldbot_group1.js
        env:
          NOCODB_API_KEY: ${{ secrets.NOCODB_API_KEY }}
          # Use a well-known Chrome executable path in the container
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable
