name: Stablecoin Yield Bot Group 1

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day
  workflow_dispatch: # Add this for manual triggering

jobs:
  scrape-yields:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      # Install Chrome for Puppeteer using the same method as the working example
      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
      
      # Create logs directory
      - name: Create directories
        run: |
          mkdir -p logs
      
      - name: Install dependencies
        run: npm install
      
      # Run yield scraper script
      - name: Run stablecoin yield bot group 1
        run: node yieldbot_group1.js
        env:
          NOCODB_API_KEY: ${{ secrets.NOCODB_API_KEY }}
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable
      
      # Upload logs as artifacts (optional but helpful for debugging)
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: yield-bot-logs
          path: logs/*.log
